---
name: Build Documentation

on:
  push:

jobs:
  test-docs:
    defaults:
      run:
        shell: bash -l {0}
    env:
      DOC_PYTHON_VERSION: '3.11'
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: load from cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: | 
            /usr/share/miniconda3
            ~/pycache
            ~/docs
          # the below two settings mean we'll alway srestore the cache
          # but the cache hit output can tell us if we have to update afterwards
          key: docs-${{ hashFiles('environment.yml')  }}
          restore-keys: |
            docs

      - name: Fail on no cache restore
        if: steps.cache.outputs.cache-matched-key == '' 
        run: |
          echo "Failed to restore any cache. exiting..."
          exit 1

      # by avoiding the mamba setup stage by loading it from cache instead we save
      # a lot of setup time, but we do have to do our own PATH management
      # hence the exports
      - name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          mamba env update -n hydromt -f environment.yml


      # run tests first so that we can also cache all of the artefacts
      - name: Generate docs
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          PYTHONPYCACHEPREFIX=~/pycache mamba run -n hydromt python -m sphinx-build docs docs/build -b dummy
