name: Linting PR description

on:
  pull_request: 
    types: [opened, reopened, edited]
  push:
    branches: [main]

jobs:
  lint-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: restore cache
        id: cache-commitlint
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo/bin
          key: commitlint
      - name: install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        if: steps.cache-commitlint.outputs.cache-hit != 'true'
      - name: compile binary
        if: steps.cache-commitlint.outputs.cache-hit != 'true'
        run: | 
          cargo install commitlint-rs
      - uses: actions/cache/save@v4
        if: steps.cache-commitlint.outputs.cache-hit != 'true'
        with:
          key: commitlint
          path: ~/.cargo/bin
      - name: Lint message
        # only do this bit for actual PRs
        if: contains(github.ref, 'refs/pull')
        env:
            PR_NUMBER: ${{ github.event.number }}
            GH_TOKEN: ${{ github.token }}
        run: |
            # abuse commit_editmsg until https://github.com/KeisukeYamashita/commitlint-rs/issues/372 is fixed
            gh pr view $PR_NUMBER --json title,body --jq ".title,.body" > ./.git/COMMIT_EDITMSG 
            commitlint --edit
