name: Linting PR description

on:
  pull_request: 
    types: [opened, reopened, edited]

jobs:
  lint-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: restore cache
        id: cache-commitlint
        uses: actions/cache/restore@v4
        with:
          path: ~/.cargo/bin
          key: commitlint
      - name: Lint message
        env:
            PR_NUMBER: ${{ github.event.number }}
            GH_TOKEN: ${{ github.token }}
        run: |
            gh pr view $PR_NUMBER --json title,body --jq ".title,.body" > lint-message.txt
            commitlint --edit lint-message.txt
            
