name: Linting PR description

on:
  pull_request: 
    types: [opened, reopened, edited]

jobs:
  lint-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install conventional_commits_linter
        env:
            PR_NUMBER: ${{ github.event.number }}
            GH_TOKEN: ${{ github.token }}
        run: |
            wget -q -O tmp.zip "https://gitlab.com/DeveloperC/conventional_commits_linter/-/jobs/artifacts/bin-0.12.0/download?job=release-binary-compiling-x86_64-linux-musl" 
            unzip tmp.zip 
            rm tmp.zip
            gh pr view $PR_NUMBER --json title,body --jq ".title,.body" | conventional_commits_linter --from-stdin
