
name: Refrech CI cache

on:
  schedule:
    - cron: 0 0 * * Sun # runs on main by default
  workflow_dispatch:

jobs:
  clear-cache:
    uses: ./.github/workflows/purge_all_caches.yml
  rebuild-cache:
    needs: clear-cache
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # python-version: ['3.10','3.11']
        python-version: ['3.10']
    name: py ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    # note absence of cucurrency, this one should only be run one at a time
    steps:
      - uses: actions/checkout@v3
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            python-version: ${{ matrix.python-version }}
            miniforge-variant: Mambaforge
            miniforge-version: latest
            use-mamba: true

      - name: Setup env
        run: |
          pip install tomli
          python make_env.py test,io,extra -p ${{ matrix.python-version}} -n hydromt
          mamba env create -f environment.yml
          mamba run -n hydromt pip install -e .

      # run tests first so that we can also cache all of the artefacts
      - name: Test
        run: mamba run -n hydromt python -m pytest --verbose --cov=hydromt --cov-report xml

      - name: Upload cache
        uses: actions/cache/save@v3
        with:
          path: | 
            /usr/share/miniconda3
          key: test-py${{ matrix.python-version }}-${{ hashFiles('environment.yml')  }}
        id: cache
