name: Tests

on:
  push:
    braches:
      - '!main'

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # python-version: ['3.10','3.11']
        python-version: ['3.10']
    name: py ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true
    steps:

      - uses: actions/checkout@v3

      # we need environment.yml to see if we have a cache hit
      - name: Generate env spec
        run: pip install tomli && python make_env.py test,io,extra -p ${{ matrix.python-version}} -n hydromt

      - name: load from cache
        id: cache
        uses: actions/cache/restore@v3
        with:
          path: | 
            /usr/share/miniconda3
          # the below two settings mean we'll alway srestore the cache
          # but the cache hit output can tell us if we have to update afterwards
          key: test-py${{ matrix.python-version }}-${{ hashFiles('environment.yml')  }}
          restore-keys: |
            test-py${{ matrix.python-version }}

      - name: Conda init
        run: |
          ls /usr/share/miniconda3
          ls /usr/share/miniconda3/etc
          ls /usr/share/miniconda3/etc/profile.d
          ls /usr/share/miniconda3/etc/profile.d/conda.sh 
          source /usr/share/miniconda3/etc/profile.d/mamba.sh 
          mamba activate base
          mamba info 
          mamba list

      # - name: Setup Mambaforge
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #       python-version: ${{ matrix.python-version }}
      #       miniforge-variant: Mambaforge
      #       miniforge-version: latest
      #       use-mamba: true

      - name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: mamba env update -n hydromt -f environment.yml

      - name: Test
        run: mamba run -n hydromt python -m pytest --verbose --cov=hydromt --cov-report xml
